name: mir-test-tools
adopt-info: mir-test-tools
summary: Mir test scripts and applications
description: Mir test scripts and applications
confinement: strict
base: core20

environment:
  LC_ALL: C.UTF-8
  XCURSOR_PATH:    $SNAP/icons
#  # XDG config
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  # Prep for Mir
  MIR_CLIENT_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/client-platform
  MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform

apps:
  smoke-test:
    command: bin/wrapper mir-smoke-test-runner

  # SDL2 example
  sdl2-test:
    command: bin/wrapper mir_demo_server --test-client neverputt
    plugs:
      - pulseaudio
    environment:
      # Alsa config
      ALSA_CONFIG_DIR: $SNAP/usr/share/alsa
      ALSA_CONFIG_PATH: ${SNAP}/usr/share/alsa
      ALSA_MIXER_SIMPLE: ${SNAP}/usr/share/alsa
      # SDL config
      PATH: $SNAP/bin/:$SNAP/usr/bin/:${SNAP}/usr/games:${PATH}
      LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio
      NEVERBALL_DATA: $SNAP/usr/share/games/neverball/

  # Qt example
  qt-test:
    command: bin/wrapper mir_demo_server --test-client $SNAP/qml/spinning-rect.sh
    environment:
      # Prep for Qt wayland
      QT_PLUGIN_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/plugins/
      QT_QPA_PLATFORM_PLUGIN_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/plugins/platforms/
      QML2_IMPORT_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/qml

  # GTK3+ example
  gtk3-test:
    command: bin/wrapper mir_demo_server --test-client $SNAP/gtkapp.sh
    environment:
      PATH: $SNAP/bin/:$SNAP/usr/bin/:${SNAP}/usr/games:${PATH}

  performance-test:
    command: bin/performance-env.sh wrapper mir_performance_tests
    plugs:
      - network-bind

  # For experimenting
  bash:
    command: bin/wrapper bash
    environment:
      # Prep for Qt wayland
      QT_PLUGIN_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/plugins/
      QT_QPA_PLATFORM_PLUGIN_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/plugins/platforms/
      QML2_IMPORT_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/qml
      # neverputt
      PATH: $SNAP/bin/:$SNAP/usr/bin/:${SNAP}/usr/games:${PATH}
      LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio
      NEVERBALL_DATA: $SNAP/usr/share/games/neverball/

plugs:
  # For Mir
  opengl:
  x11:
  login-session-control:
  # For GTK3+
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

slots:
  wayland:

layout:
  /usr/share:
    bind: $SNAP/usr/share
  /usr/bin/Xwayland:
    symlink: $SNAP/usr/bin/Xwayland
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp

parts:
  ppa-setup:
    plugin: nil
    override-pull: |
      sudo apt --assume-yes install software-properties-common
      sudo add-apt-repository -yn ppa:mir-team/rc
      sudo add-apt-repository -yu ppa:graphics-drivers/ppa
      snapcraftctl pull

  recipe-version:
    plugin: nil
    source: .
    source-type: git
    override-build: |
      git rev-list --count HEAD > $SNAPCRAFT_PART_INSTALL/recipe-version
    prime:
      - -recipe-version

  mir-test-tools:
    after: [ recipe-version, ppa-setup ]
    plugin: nil
    override-pull: |
      snapcraftctl pull
      mir_version=`LANG=C apt-cache policy mir-test-tools | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
      recipe_version=`cat $SNAPCRAFT_STAGE/recipe-version`
      snapcraftctl set-version $mir_version-snap$recipe_version
      if echo $mir_version | grep dev; then snapcraftctl set-grade devel; else snapcraftctl set-grade stable; fi
    stage-packages:
    - fonts-freefont-ttf
    - mir-graphics-drivers-desktop
    - mir-test-tools
    - glmark2-es2
    - glmark2-data
    - glmark2-es2-wayland
    - on amd64: [mir-graphics-drivers-nvidia]

  icons:
    plugin: nil
    stage-packages: [dmz-cursor-theme]

  mesa:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri

  sdl2-apps:
    plugin: nil
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-net-2.0-0
      - libpulse0
      # SDL2 games
      - neverputt

  qmldemo:
    plugin: dump
    source: qmldemo
    stage-packages:
      - qmlscene
      - qtwayland5
      - qml-module-qtquick2
    organize:
      spinning-rect.qml: qml/spinning-rect.qml
      spinning-rect.sh: qml/spinning-rect.sh

  snapcraft-desktop-helpers:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      # desktop-launch doesn't handle running without a user session very well, this avoids slow startup here
      sed --in-place s'/^  needs_update=true/:/' $SNAPCRAFT_PART_INSTALL/bin/desktop-launch

  gtk3-apps:
    plugin: nil
    stage-packages:
      - gnome-sudoku

  gtk3app:
    plugin: dump
    source: gtk3

  performance:
    plugin: dump
    source: performance
    organize:
      performance-env.sh: bin/performance-env.sh

  wrapper:
    plugin: dump
    stage-packages: [bash]
    source: wrapper
    organize:
      wrapper: bin/wrapper

  xwayland:
    plugin: nil
    stage-packages:
      - xwayland
      - libbz2-1.0
